@Backend_HostAddress = http://localhost:5041
###
POST {{Backend_HostAddress}}/auth/register
Content-Type: application/json
Accept: application/json

{
  "name": "John Doe",
  "Email": "john.doe@example.com",
  "Password": "JohnDoe@123"
}
###
POST {{Backend_HostAddress}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "john.doe@example.com",
  "password": "JohnDoe@123"
}
###
GET {{Backend_HostAddress}}/auth/getUsers
Authorization: Bearer <YOUR_ACCESS_TOKEN_HERE>
###
POST {{Backend_HostAddress}}/auth/refresh
Content-Type: application/json
Accept: application/json

{
  "refreshToken": "<YOUR_REFRESH_TOKEN_HERE>"
}