@Backend_HostAddress = http://localhost:5041
@contentType = application/json
###
POST {{Backend_HostAddress}}/auth/register
Content-Type: {{contentType}}

{
  "name": "John Doe",
  "email": "john.doe66@example.com",
  "password": "JohnDoe@123"
}
###
# @name login
POST {{Backend_HostAddress}}/auth/login
Content-Type: {{contentType}}

{
  "email": "kevinpatel2383@gmail.com",
  "password": "Kevin@123"
  // "email": "john.doe66@example.com",
  // "password": "JohnDoe@123"
}
###
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNCIsImVtYWlsIjoia2V2aW5wYXRlbDIzODNAZ21haWwuY29tIiwicm9sZSI6IkNhbmRpZGF0ZSIsInRva2VuX3VzZSI6ImFjY2VzcyIsImp0aSI6ImY4MGU0MzkzLWZkOWEtNDliNS04OWZiLTA4MzFiOTBkYTQyMyIsImV4cCI6MTc2MjkzMjg4MSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDQxIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDQxIn0.VP2BDpL3nnjiZe6KxjvGrGwLrpSgWz8oPlYOxIiYzGk
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNCIsImVtYWlsIjoia2V2aW5wYXRlbDIzODNAZ21haWwuY29tIiwicm9sZSI6IkNhbmRpZGF0ZSIsInRva2VuX3VzZSI6InJlZnJlc2giLCJqdGkiOiI0ZWMyMDViOS0zZTY3LTQwMzEtODZlNy05MDZiY2Q3YjVhMTEiLCJleHAiOjE3NjI5Mzg1NTAsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTA0MSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTA0MSJ9.g-vKlDF2lsap53O_iexITeYRiAd_7q7h2SfhYVAC3qw
###
POST {{Backend_HostAddress}}/auth/refresh
Content-Type: {{contentType}}

{
  "refreshToken": "{{refreshToken}}"
}
###
GET {{Backend_HostAddress}}/positions
Authorization: Bearer {{authToken}}
Accept: {{contentType}}

HTTP/1.1 401  - Unauthorized
content-length: 0
connection: close
date: Wed, 12 Nov 2025 10:29:05 GMT
server: Kestrel
www-authenticate: Bearer error="invalid_token", error_description="The token expired at '11/12/2025 07:34:41'"
###
GET {{Backend_HostAddress}}/positions/my-positions
Authorization: Bearer {{authToken}}
Accept: {{contentType}}
###
GET {{Backend_HostAddress}}/positions/1
Authorization: Bearer {{authToken}}
Accept: {{contentType}}
###
POST {{Backend_HostAddress}}/positions
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}

{
  "title": "Senior Software Engineer 2",
  "description": "Random: lorem ipsum dolor sit amet consectetur adipiscing elit. Lorem ipsum dolor sit amet consectetur adipiscing elit.",
  "yearsOfExperienceRequired": 2
}
###
PUT {{Backend_HostAddress}}/positions/8
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}

{
  "description": "Senior Software Engineer (Updated)",
  "status": "closed",
  "reasonForClosure": "Position filled"
}
###
DELETE {{Backend_HostAddress}}/positions/7
Authorization: Bearer {{authToken}}
###
GET {{Backend_HostAddress}}/auth/getUsers
Authorization: Bearer {{authToken}}